### ISSUE TITLE
Support for binaries?

### ISSUE THREAD

**Issue by CamsShaft** [AndroidIDE-CN/AIDE-Plus#2]
Hello, I'm looking forward to trying out your app and I know it's very new, I was just wondering if it will support the AIDE NDK Binaries addon eventually. I think it's because the package name is different than the other AIDE app so it doesn't recognize that it's even installed. Would it be okay if I just changed the package name and recompiled it if that's the case? Or if there's something else that needs to be done, with the right instructions I could do it myself. Thanks and hope things progress smoothly for you. Here's a picture for reference...

![Screenshot_20240520_145425_One UI Home](https://github.com/ZeroAicy/AIDE-Plus/assets/141678661/c6cddb3e-332b-4fed-9557-0587519b5dcd)

**Comment by CamsShaft** [comment]
Tried swapping sharedUserId's to match but that didn't make a difference. I've had this happen before and never figured out how to do it. It feels like it would be a pretty easy fix but I don't have the years of experience in this.

**Comment by ZeroAicy** [comment]
Actually, the original Ndk support in AIDE is quite outdated. You can modify the installation script from https://github.com/MrIkso/AndroidIDE-NDK to achieve Ndk installation. Additionally, since the original target version is 29, the Ndk native executable projects are installed and run by compiling an executor (apk), which is quite cumbersome. Although I changed the target version to 28, other parts still need to be modified.

To simulate the AIDE Ndk structure using the ln command, you can do the following:

For example:
`rm -rf /data/user/0/${PackageName}/no_backup/ndksupport-1710240003 `
`mkdir -p /data/user/0/${PackageName}/no_backup/ndksupport-1710240003 `
  
`touch /data/user/0/${PackageName}/no_backup/ndksupport-1710240003/.installed`
  
`ln -s /data/user/0/${PackageName}/files/framework/android-sdk/ndk/24.0.8215888`
`/data/user/0/${PackageName}/no_backup/ndksupport-1710240003/android-ndk-aide`
  
`ln -s /data/user/0/${PackageName}/files/usr/bin/applets`
`/data/user/0/${PackageName}/no_backup/ndksupport-1710240003/bin`
At the same time, you will need a busybox.

Please note that ${PackageName} should be replaced with the actual package name of your application. Also, make sure you have the necessary permissions to create and modify files in the /data/user/0/ directory.

**Comment by ZeroAicy** [comment]
You can also support cmake projects, but the gradle parsing does not have extensions, so the cmake configuration needs to be hardcoded. I have made modifications to this in other versions of AIDE [AIDE Pro], so I haven't included it in AIDE+. Additionally, I currently don't have a need for Ndk, and it's wasteful to install a separate Ndk for each AIDE. My vision is to utilize a standalone software to configure an Ndk environment, and then invoke and return information via broadcasts or other methods. This way, the Ndk can be reused instead of installing multiple Ndk instances.

**Comment by CamsShaft** [comment]
Well I certainly didn't expect you to go all out in your reply haha. I appreciate all the information and realize what a mess it is. Why does android keep using utilities and tools that, from the sounds of it, are outdated. Termux can be really annoying for what you mentioned here: "Additionally, I currently don't have a need for Ndk, and it's wasteful to install a separate Ndk for each AIDE." Trying to compile a simple C program and many other things typically don't work because clang isn't the right one, same with gcc or you have to manually hunt down the proper files for the includes folder. I like your idea a lot!

**Comment by ZeroAicy** [comment]
但这不是我主要的要做的，其实修复底包dex才是我要做的，我修复了很多类，字段和方法，比如AIDE的代码分析模型[codemodel]，因此可能对Ndk的支持会推迟很久

**Comment by CamsShaft** [comment]
Hey no worries. I'm just one guy, besides there's lot of other apps. I really just enjoy trying new (to me) apps out to see how they are and what differences there are between similar ones. Helps with efficiency shaving off a few extra minutes if someone did something a bit different with almost the same app.

**Comment by hasanelfalakiy** [comment]
> But this is not my main task. Actually, fixing the base package dex is what I need to do. I have fixed many classes, fields, and methods, such as AIDE's code analysis model [codemodel], so support for Ndk may be delayed for a long time

Does it support Kotlin and code completion?

**Comment by ZeroAicy** [comment]
> > But this is not my main task. Actually, fixing the base package dex is what I need to do. I have fixed many classes, fields, and methods, such as AIDE's code analysis model [codemodel], so support for Ndk may be delayed for a long time
> 
> Does it support Kotlin and code completion?

In fact, only Kotlin lexical highlighting is available.

I am fixing the AIDE package dex and trying to add Lambda expressions. I have now made the Java parser support parsing Lambda expressions

**Comment by hasanelfalakiy** [comment]
Is this the original AIDE that was previously published on the Play Store?

**Comment by ZeroAicy** [comment]
> Quote reply

No, it was expanded on the latest official version

**Comment by ZeroAicy** [comment]
> Is this the original AIDE that was previously published on the Play Store?

No, it was expanded on the latest official version

**Comment by hasanelfalakiy** [comment]
> > Is this the original AIDE that was previously published on the Play Store?
> 
> No, it was expanded on the latest official version

ohh, so the developer is the original owner, aren't you?

**Comment by ZeroAicy** [comment]
> > > Is this the original AIDE that was previously published on the Play Store?
> > 
> > 
> > No, it was expanded on the latest official version
> 
> ohh, so the developer is the original owner, aren't you?

no

**Comment by hasanelfalakiy** [comment]
> > > > Is this the original AIDE that was previously published on the Play Store?
> > > 
> > > 
> > > No, it was expanded on the latest official version
> > 
> > ohh, so the developer is the original owner, aren't you?
> 
> no

oh okay, Will the auto complete and suggestion code feature be added later?

**Comment by ZeroAicy** [comment]
> > > > > Is this the original AIDE that was previously published on the Play Store?
> > > > 
> > > > 
> > > > No, it was expanded on the latest official version
> > > 
> > > 
> > > ohh, so the developer is the original owner, aren't you?
> > 
> > 
> > no
> 
> oh okay, Will the auto complete and suggestion code feature be added later?

I don't know Kotlin, so I probably won't support it because AIDE's codemodel is customized and needs to be written separately for Kotlin's codemodel

**Comment by hasanelfalakiy** [comment]
> > > > > > Is this the original AIDE that was previously published on the Play Store?
> > > > > 
> > > > > 
> > > > > No, it was expanded on the latest official version
> > > > 
> > > > 
> > > > ohh, so the developer is the original owner, aren't you?
> > > 
> > > 
> > > no
> > 
> > oh okay, Will the auto complete and suggestion code feature be added later?
> 
> I don't know Kotlin, so I probably won't support it because AIDE's codemodel is customized and needs to be written separately for Kotlin's codemodel
> 

oh okay,,

**Comment by ZeroAicy** [comment]
You can use https://github.com/ZeroAicy/AIDE-Ndk-Install
